version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
        environment:
          NODE_ENV: test
          DATABASE_URL: postgres://root@localhost/sms_test
          DATABASE_DIALECT: postgres
          PORT: 5000
      - image: postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: sms_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Wait for postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # run tests!
      - run: yarn test
